var searchData=
[
  ['etemperatureaveragingthermistor_47',['eTemperatureAveragingThermistor',['../thermistor_8h.html#a0858366f11635b0d5edcd23f10091589',1,'eTemperatureAveragingThermistor(handle_t xStream, uint8_t ucLength, const xThermistorTemperature_t *pxTemperatureTable, float *pfTemperatureReaded):&#160;thermistor.c'],['../thermistor_8c.html#a0858366f11635b0d5edcd23f10091589',1,'eTemperatureAveragingThermistor(handle_t xStream, uint8_t ucLength, const xThermistorTemperature_t *pxTemperatureTable, float *pfTemperatureReaded):&#160;thermistor.c']]],
  ['ethermistoranalogreadmv_48',['eThermistorAnalogReadmV',['../thermistor_8h.html#a8180a10e615b64caaf0387afe7d385fb',1,'thermistor.h']]],
  ['ethermistorcircuitgetthermistance_49',['eThermistorCircuitGetThermistance',['../thermistor_circuit_8h.html#aed69a032a66c1a64e3e4adfe977a5f50',1,'eThermistorCircuitGetThermistance(handle_t xStream, xThermistorCircuitConfig_t xThermistorCircuitConfig, uint32_t *pulThermistance):&#160;thermistorCircuit.c'],['../thermistor_circuit_8c.html#aed69a032a66c1a64e3e4adfe977a5f50',1,'eThermistorCircuitGetThermistance(handle_t xStream, xThermistorCircuitConfig_t xThermistorCircuitConfig, uint32_t *pulThermistance):&#160;thermistorCircuit.c']]],
  ['ethermistorcircuitutilgetthermistancevalue_50',['eThermistorCircuitUtilGetThermistanceValue',['../thermistor_circuit_util_8h.html#adf006a51b592cc8a298bc15605f89c7b',1,'eThermistorCircuitUtilGetThermistanceValue(handle_t xStream, xThermistorCircuitConfig_t xThermistorCircuitConfig, uint32_t *pulThermistance):&#160;thermistorCircuitUtil.c'],['../thermistor_circuit_util_8c.html#adf006a51b592cc8a298bc15605f89c7b',1,'eThermistorCircuitUtilGetThermistanceValue(handle_t xStream, xThermistorCircuitConfig_t xThermistorCircuitConfig, uint32_t *pulThermistance):&#160;thermistorCircuitUtil.c']]],
  ['ethermistorgettemperaturebeta_51',['eThermistorGetTemperatureBeta',['../thermistor_8h.html#abe60b8ef5c9a7ecc2926df1e750a737f',1,'eThermistorGetTemperatureBeta(handle_t xStream, uint32_t ulBetaCoefficient, xThermistorCircuitConfig_t xThermistorCircuitConfig, eThermistorType_t eThermistorType, float *pfTemperature):&#160;thermistor.c'],['../thermistor_8c.html#abe60b8ef5c9a7ecc2926df1e750a737f',1,'eThermistorGetTemperatureBeta(handle_t xStream, uint32_t ulBetaCoefficient, xThermistorCircuitConfig_t xThermistorCircuitConfig, eThermistorType_t eThermistorType, float *pfTemperature):&#160;thermistor.c']]],
  ['ethermistorgettemperaturetable_52',['eThermistorGetTemperatureTable',['../thermistor_8h.html#a2eb378796930d13411ae6a6b1da9c8dd',1,'eThermistorGetTemperatureTable(handle_t xStream, xThermistorCircuitConfig_t xThermistorCircuitConfig, const xThermistorTemperature_t *pxTemperatureTable, uint8_t ucLength, float *pfTemperature):&#160;thermistor.c'],['../thermistor_8c.html#a2eb378796930d13411ae6a6b1da9c8dd',1,'eThermistorGetTemperatureTable(handle_t xStream, xThermistorCircuitConfig_t xThermistorCircuitConfig, const xThermistorTemperature_t *pxTemperatureTable, uint8_t ucLength, float *pfTemperature):&#160;thermistor.c']]],
  ['ethermistorinitbasecircuit_53',['eThermistorInitBaseCircuit',['../thermistor_8h.html#add0fcf3c8f0bb8d04a1cb10b99a56fb4',1,'eThermistorInitBaseCircuit(xThermistorCircuitConfig_t *pxThermistorCircuitConfig, uint32_t ulSeriesResistor1, uint32_t ulSeriesResistor2, uint16_t usReferenceVoltagemV):&#160;thermistor.c'],['../thermistor_8c.html#add0fcf3c8f0bb8d04a1cb10b99a56fb4',1,'eThermistorInitBaseCircuit(xThermistorCircuitConfig_t *pxThermistorCircuitConfig, uint32_t ulSeriesResistor1, uint32_t ulSeriesResistor2, uint16_t usReferenceVoltagemV):&#160;thermistor.c']]],
  ['ethermistorlogarithm_54',['eThermistorLogarithm',['../thermistor_8h.html#a7ebea4cdaf41d4c999eb778f248c8941',1,'thermistor.h']]]
];
